resources = ['W', 'S', 'O', 'B', 'G', 'P', 'L']
choice_resources = ['W/S', 'W/O', 'W/B', 'S/O', 'S/B', 'O/B', 'W/S/O/B', 'G/P/L']
sciences = ['wheel', 'compass', 'tablet']
colors = ['brown', 'grey', 'yellow', 'blue', 'green', 'red', 'purple']
effects = ['production', 'discount', 'gold', 'points', 'science', 'military',
           'perBoardElement', 'action']
boards = ['SELF', 'LEFT', 'RIGHT']
providers = ['LEFT_PLAYER', 'RIGHT_PLAYER']
types = ['CARD', 'BUILT_WONDER_STAGES', 'COMPLETED_WONDER']
action = ['PLAY_LAST_CARD', 'PLAY_DISCARDED', 'FIRST_FREE_PER_COLOR',
          'FIRST_FREE_PER_AGE', 'LAST_FREE_PER_AGE']
guilds = ['arena', 'chamber of commerce', 'haven', 'lighthouse', 'ludus',
          'builders guild', 'craftsmens guild', 'magistrates guild',
          'philosophers guild', 'shipowners guild', 'spies guild',
          'decorators guild', 'traders guild', 'workers guild']

chain_dict = {'Caravansery': 0,
              'Forum': 1,
              'Aqueduct': 2,
              'Courthouse': 3,
              'Statue': 4,
              'Dispensary': 5,
              'Laboratory': 6,
              'Library': 7,
              'Archery Range': 8,
              'Stables': 9,
              'Arena': 10,
              'Haven': 11,
              'Lighthouse': 12,
              'Gardens': 13,
              'Pantheon': 14,
              'Senate': 15,
              'Academy': 16,
              'Lodge': 17,
              'Observatory': 18,
              'Study': 19,
              'University': 20,
              'Circus': 21,
              'Fortifications': 22,
              'Siege Workshop': 23}

card_dict = {'Clay Pit': 0,
             'Clay Pool': 1,
             'Excavation': 2,
             'Forest Cave': 3,
             'Lumber Yard': 4,
             'Mine': 5,
             'Ore Vein': 6,
             'Stone Pit': 7,
             'Timber Yard': 8,
             'Tree Farm': 9,
             'Glassworks': 31,
             'Loom': 32,
             'Press': 33,
             'East Trading Post': 13,
             'Marketplace': 14,
             'Tavern': 15,
             'West Trading Post': 16,
             'Altar': 17,
             'Baths': 18,
             'Well': 19,
             'Theater': 20,
             'Apothecary': 21,
             'Scriptorium': 22,
             'Workshop': 23,
             'Barracks': 24,
             'Guard Tower': 25,
             'Stockade': 26,
             'Brickyard': 27,
             'Foundry': 28,
             'Quarry': 29,
             'Sawmill': 30,
             'Bazar': 34,
             'Caravansery': 35,
             'Forum': 36,
             'Vineyard': 37,
             'Aqueduct': 38,
             'Courthouse': 39,
             'Statue': 40,
             'Temple': 41,
             'Dispensary': 42,
             'Laboratory': 43,
             'Library': 44,
             'School': 45,
             'Archery Range': 46,
             'Stables': 47,
             'Training Ground': 48,
             'Walls': 49,
             'Arena': 50,
             'Chamber of Commerce': 51,
             'Haven': 52,
             'Lighthouse': 53,
             'Ludus': 54,
             'Gardens': 55,
             'Palace': 56,
             'Pantheon': 57,
             'Senate': 58,
             'Town Hall': 59,
             'Academy': 60,
             'Lodge': 61,
             'Observatory': 62,
             'Study': 63,
             'University': 64,
             'Arsenal': 65,
             'Castrum': 66,
             'Circus': 67,
             'Fortifications': 68,
             'Siege Workshop': 69,
             'Builders Guild': 70,
             'Craftsmens Guild': 71,
             'Magistrates Guild': 72,
             'Philosophers Guild': 73,
             'Scientists Guild': 74,
             'Shipowners Guild': 75,
             'Spies Guild': 76,
             'Decorators Guild': 77,
             'Traders Guild': 78,
             'Workers Guild': 79}

wonder_dict = {('Alexandria', 'A', 1): 0,
               ('Alexandria', 'A', 2): 1,
               ('Alexandria', 'A', 3): 2,
               ('Alexandria', 'B', 1): 3,
               ('Alexandria', 'B', 2): 4,
               ('Alexandria', 'B', 3): 5,
               ('Babylon', 'A', 1): 6,
               ('Babylon', 'A', 2): 7,
               ('Babylon', 'A', 3): 8,
               ('Babylon', 'B', 1): 9,
               ('Babylon', 'B', 2): 10,
               ('Babylon', 'B', 3): 11,
               ('Ephesos', 'A', 1): 12,
               ('Ephesos', 'A', 2): 13,
               ('Ephesos', 'A', 3): 14,
               ('Ephesos', 'B', 1): 15,
               ('Ephesos', 'B', 2): 16,
               ('Ephesos', 'B', 3): 17,
               ('Gizah', 'A', 1): 18,
               ('Gizah', 'A', 2): 19,
               ('Gizah', 'A', 3): 20,
               ('Gizah', 'B', 1): 21,
               ('Gizah', 'B', 2): 22,
               ('Gizah', 'B', 3): 23,
               ('Gizah', 'B', 4): 24,
               ('Halikarnassus', 'A', 1): 25,
               ('Halikarnassus', 'A', 2): 26,
               ('Halikarnassus', 'A', 3): 27,
               ('Halikarnassus', 'B', 1): 28,
               ('Halikarnassus', 'B', 2): 29,
               ('Halikarnassus', 'B', 3): 30,
               ('Olympia', 'A', 1): 31,
               ('Olympia', 'A', 2): 32,
               ('Olympia', 'A', 3): 33,
               ('Olympia', 'B', 1): 34,
               ('Olympia', 'B', 2): 35,
               ('Olympia', 'B', 3): 36,
               ('Rhodos', 'A', 1): 37,
               ('Rhodos', 'A', 2): 38,
               ('Rhodos', 'A', 3): 39,
               ('Rhodos', 'B', 1): 40,
               ('Rhodos', 'B', 2): 41}
